name: "💡 ​Missing or deprecated roadmap topics"
description: Help us improve the roadmaps by suggesting changes
labels: [topic-change]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve the roadmaps with your suggestions.
  - type: dropdown
    id: roadmap
    attributes:
      label: Roadmap
      description: What roadmap are you referring to?
      options:
        - SAP ABAP Developer
        - SAP UX Developer
        - SAP Cloud Developer
        - SAP Integration Developer
    validations:
      required: true
  - type: textarea
    id: roadmap-suggestions
    attributes:
      label: Suggestions
      description: What changes would you like to suggest?
      placeholder: Enter your suggestions here.
    validations:
      required: true
